Resources:
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: CPR Test Repository
      Triggers:
        - DestinationArn: !GetAtt PostPushHookLambdaFunction.Arn
          Name: ChangeLambda
          Events: ['all']
Outputs:
  SSHURLCodeCommitRepository:
    Value: !GetAtt CodeCommitRepository.CloneUrlSsh