Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Function:
            Fn::GetAtt:
            - TestFunction
            - Arn
        - Event: s3:ObjectRemoved:*
          Function:
            Fn::GetAtt:
            - TestFunction
            - Arn


  TestBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function:
              Fn::GetAtt:
                - TestFunctionS3
                - Arn
          - Event: s3:ObjectRemoved:*
            Function:
              Fn::GetAtt:
                - TestFunctionS3
                - Arn

